### ISSUE TITLE
Input: "Friday 15th Jul", format "dddd Do MMM" parses wrong month

### ISSUE THREAD

**Issue by gajus** [taylorhakes/fecha#15]
> Input: "Friday 15th Jul"
> Format "dddd Do MMM"
> Output: 2016-01-15
> Expected output: 2016-07-15

**Comment by gajus** [comment]
It looks like the reason for this is that `Do` is being treated the same way as `DD`.

https://github.com/taylorhakes/fecha/blob/master/fecha.js#L198

As a result `MMM` is actually picking up `th ` as opposed to `Jul`.

**Comment by taylorhakes** [comment]
Thanks for the bug report. I am unable to fix bugs until Tuesday. If you submit a pull request with a fix, I can merge it and get it fixed.

**Comment by rhalff** [comment]
@taylorhakes I've added a pull request to fix this issue.

Although there are tests already using the ordinal variant they pass only because of the way the date is written:

See: https://github.com/taylorhakes/fecha/blob/master/test.js#L45-L54

For the date `def 3rd, 2021` the leftover part (dateStr) is `rd, 2021` the next pass then matches `/\d{4}/` so the year is parsed correctly.

However when `Friday 15th Jul` is used the leftover part is `th Jul` and the `word` rule will try to match `th` with a month name, which fails.

This fix will correctly parse out `15th` and the `parseInt` then converts it to 15.

`dateStr`  will then correctly be ` Jul` and the part will be parsed correctly.

**Comment by taylorhakes** [comment]
Fixed in version 2.2.0. 4fe1536

**Comment by gajus** [comment]
What was the reason for bumping the minor version for a bug fix?

**Comment by taylorhakes** [comment]
It should have been a patch release. I was incorrectly thinking it was new functionality. Fortunately, minor version changes for patch level changes are allowed.
