### ISSUE TITLE
fecha.format force specific timezone

### ISSUE THREAD

**Issue by throrin19** [taylorhakes/fecha#25]
Hi,

It's possible to add tjhe possibility to force the format function with specific timezone ? 

Actually, If I pass an UTC date in my brwoser, the formatted date is converted into the local timezone (Europe/Paris). 

But, I want show the date in UTC format (or get a part of this date in the UTC timezone like juste the hour part).

Thanks

**Comment by taylorhakes** [comment]
There isn't a really nice way to do that. The best way I can think of is add `+0000` to your date string and using the `ZZ` parse flag. This will make the parser use UTC.

**Comment by throrin19** [comment]
I made this for the string date but I talk about the real Date Object. Okay it's in UTC but the browser convert it, on display, on the current user timezone

**Comment by taylorhakes** [comment]
This library doesn't affect how the real Date objects behave in javascript. If you want to create a UTC date in regular javascript, this library won't help you.
Here is an example of how to do it.

```js
var myDate = new Date(2015,11,1,4,10);
console.log(myDate.getHours()); // 4 , Current timezone

var myTimestampUTC = Date.UTC(myDate.getFullYear(), myDate.getMonth(), myDate.getDate(), myDate.getHours(), myDate.getMinutes())
var myDateUTC = new Date(myTimestampUTC);
console.log(myDateUTC.getHours()); // 23, UTC
```
https://jsbin.com/lacoduyiqa/edit?js,console

**Comment by GistOfSpirit** [comment]
Hi,

Would you reconsider this issue? JavaScript itself can display the UTC components of any Date object instead of local (by using `getUTCHours()` instead of `getHours()`, and so on) so it's only a matter of modifying fecha to call these methods in certain conditions.

I actually made a variant like this and I'll be using it for my own purposes, I can open a pull request if you would accept this as an option.
